# kubectl port-forward pod-sencillo 5555:5000
# http://localhost:5555/python
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: pod-sencillo-testing
  name: pod-sencillo
spec:
  containers:
    - image: 'jorgecardona/test-kubernetes-ip-python-3.10.5:v1'
      name: pod-testing
      ports:
        - name: container-port
          containerPort: 5000
          hostPort: 5000
          
      livenessProbe:
        httpGet:
          path: /python
          port: container-port # reemplazado por el nombre del puerto definido en puertos
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 3
        failureThreshold: 4
        
      readinessProbe:
        httpGet:
          path: /python
          port: 5000
        initialDelaySeconds: 5
        timeoutSeconds: 2
        periodSeconds: 3
        failureThreshold: 4
